name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-slim
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v4.2.0
        with:
          version: 10.33.0
          run_install: false

      - run: pnpm install --frozen-lockfile -P

      - run: pnpm run build

      - run: zip -r postonx-chrome-mv3.zip ".output/chrome-mv3"

      - uses: softprops/action-gh-release@v2
        with:
          files: postonx-chrome-mv3.zip
